apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: hpa-example
spec:
    replicas: 1
    template:
        metadata:
            name: hpa-example
            labels:
                app: hpa-example
        spec:
            containers:
            - name: hpa-example
              image: superseb/rancher-demo
              ports:
              - name: http-port
                containerPort: 80
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: hpa-example-autoscaler
spec:
    scaleTargetRef:
        apiVersion: extensions/v1beta1
        kind: Deployment
        name: hpa-example
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 10i



kubectl autoscale deployment hpa-example --cpu-percent=50 --min=1 --max=3
kubectl run hpa-example --image=superseb/rancher-demo --requests=cpu=200m --expose --port=8080


kubectl run -i --tty load-generator --image=busybox /bin/sh

Hit enter for command prompt

while true; do wget -q -O- http://13.211.191.51:30279/; done
